// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class InitResult {
    /**
     * Creates a new InitResult instance.
     * @param {Partial<InitResult>} [$$source = {}] - The source object to create the InitResult.
     */
    constructor($$source = {}) {
        if (!("needsOnboarding" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["needsOnboarding"] = false;
        }
        if (!("needsVerification" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["needsVerification"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InitResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InitResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InitResult(/** @type {Partial<InitResult>} */($$parsedSource));
    }
}
