name: Build Release

permissions:
  contents: write
  actions: write

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      release_url:
        description: 'Release upload URL'
        required: true

jobs:
  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true
        
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Wails Dependencies
        run: |
          mkdir -p ../github
          cd ../github
          git clone https://github.com/wailsapp/wails.git
          cd wails
          git checkout v3-alpha
          cd v3/cmd/wails3
          go install
          cd ../../../..

      - name: Update go.mod
        run: |
          sed -i '' 's|../../Project/github/wails/v3|../github/wails/v3|g' go.mod

      - name: Build Release Binaries
        run: |
          mkdir -p darwinBinaries
          wails3 doctor
          wails3 package
          zip -r Clave.zip bin/Clave.app
          mv Clave.zip darwinBinaries/

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event_name == 'workflow_dispatch' && inputs.release_url || github.event.release.upload_url }}
          asset_path: darwinBinaries/Clave.zip
          asset_name: Clave-macos.zip
          asset_content_type: application/zip

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true

      # - name: Install Scoop and NSIS
      #   uses: MinoruSekine/setup-scoop@v4.0.1
      #   with:
      #     apps: nsis

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Wails Dependencies
        shell: cmd
        run: |
          mkdir ..\github
          cd ..\github
          git clone https://github.com/wailsapp/wails.git
          cd wails
          git checkout v3-alpha
          cd v3\cmd\wails3
          go install
          cd ..\..\..\..

      - name: Update go.mod
        shell: pwsh
        run: |
          (Get-Content go.mod) -replace '../../Project/github/wails/v3', '../github/wails/v3' | Set-Content go.mod

      - name: Build Release Binaries
        run: |
          mkdir windowsBinaries
          wails3 doctor
          wails3 package
          Compress-Archive -Path bin\Clave.exe -DestinationPath windowsBinaries\Clave.zip

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event_name == 'workflow_dispatch' && inputs.release_url || github.event.release.upload_url }}
          asset_path: windowsBinaries/Clave.zip
          asset_name: Clave-windows.zip
          asset_content_type: application/zip

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev gcc libgtk-3-dev pkg-config

      - name: Setup Wails Dependencies
        run: |
          mkdir -p ../github
          cd ../github
          git clone https://github.com/wailsapp/wails.git
          cd wails
          git checkout v3-alpha
          cd v3/cmd/wails3
          go install
          cd ../../../..

      - name: Update go.mod
        run: |
          sed -i 's|../../Project/github/wails/v3|../github/wails/v3|g' go.mod

      - name: Build Release Binaries
        run: |
          mkdir -p linuxBinaries
          wails3 doctor
          wails3 package
          zip -r Clave.zip bin/Clave
          mv Clave.zip linuxBinaries/

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event_name == 'workflow_dispatch' && inputs.release_url || github.event.release.upload_url }}
          asset_path: linuxBinaries/Clave.zip
          asset_name: Clave-linux.zip
          asset_content_type: application/zip