name: Build Release

permissions:
  contents: write
  actions: write

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      release_url:
        description: 'Release upload URL'
        required: true

jobs:
  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true
        
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Wails Dependencies
        run: |
          mkdir -p ../github
          cd ../github
          git clone https://github.com/wailsapp/wails.git
          cd wails
          git checkout v3-alpha
          cd v3/cmd/wails3
          go install
          cd ../../../..

      - name: Update go.mod
        run: |
          sed -i '' 's|../wails/v3|../github/wails/v3|g' go.mod

      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
          p12-password: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}

      - name: Build and Sign Release Binaries
        run: |
          mkdir -p darwinBinaries
          wails3 doctor
          wails3 task common:update:build-assets
          wails3 package
          codesign --deep --force --verbose --options=runtime --sign ${{ secrets.APPLE_SIGNING_IDENTITY}} bin/Clave.app/Contents/MacOS/Clave
          codesign --deep --force --verbose --options=runtime --sign ${{ secrets.APPLE_SIGNING_IDENTITY}} bin/Clave.app
          npm install --global create-dmg
          create-dmg bin/Clave.app --dmg-title Clave-${{ github.event.release.tag_name }}
          for dmg in *.dmg; do
            mv "$dmg" "darwinBinaries/Clave-${{ github.event.release.tag_name }}--arm64.dmg"
            echo "arm64DMGPath=darwinBinaries/Clave-${{ github.event.release.tag_name }}--arm64.dmg" >> $GITHUB_ENV
            codesign --force --verbose --options=runtime --sign ${{ secrets.APPLE_SIGNING_IDENTITY}} ${{ env.arm64DMGPath }}
          done
          ls -alh bin

      - name: Notarize Release Binaries
        run: |
          xcrun notarytool submit ${{ env.arm64DMGPath }} --apple-id ${{ secrets.MACOS_SIGNING_GON_USERNAME }} --team-id ${{secrets.APPLE_DEVELOPER_TEAM_ID}} --password ${{ secrets.MACOS_SIGNING_GON_APPLICATION_PASSWORD }} --verbose --wait 
          xcrun stapler staple ${{ env.arm64DMGPath }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event_name == 'workflow_dispatch' && inputs.release_url || github.event.release.upload_url }}
          asset_path: ${{ env.arm64DMGPath }}
          asset_name: Clave-${{ github.event.release.tag_name }}--arm64.dmg
          asset_content_type: application/x-apple-diskimage

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Wails Dependencies
        shell: cmd
        run: |
          mkdir ..\github
          cd ..\github
          git clone https://github.com/wailsapp/wails.git
          cd wails
          git checkout v3-alpha
          cd v3\cmd\wails3
          go install
          cd ..\..\..\..

      - name: Update go.mod
        shell: pwsh
        run: |
          (Get-Content go.mod) -replace '../wails/v3', '../github/wails/v3' | Set-Content go.mod

      - name: Build Release Binaries
        run: |
          mkdir windowsBinaries
          wails3 doctor
          wails3 task common:update:build-assets
          wails3 package
          dir /alh /b /a-d bin
          Compress-Archive -Path bin\Clave.exe -DestinationPath windowsBinaries\Clave.zip

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event_name == 'workflow_dispatch' && inputs.release_url || github.event.release.upload_url }}
          asset_path: windowsBinaries/Clave.zip
          asset_name: Clave-windows.zip
          asset_content_type: application/zip

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev gcc libgtk-3-dev pkg-config

      - name: Setup Wails Dependencies
        run: |
          mkdir -p ../github
          cd ../github
          git clone https://github.com/wailsapp/wails.git
          cd wails
          git checkout v3-alpha
          cd v3/cmd/wails3
          go install
          cd ../../../..

      - name: Update go.mod
        run: |
          sed -i 's|../wails/v3|../github/wails/v3|g' go.mod

      - name: Build Release Binaries
        run: |
          mkdir -p linuxBinaries
          wails3 doctor
          wails3 task common:update:build-assets
          wails3 package
          zip -r Clave.zip bin/Clave
          mv Clave.zip linuxBinaries/
          ls -alh bin

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event_name == 'workflow_dispatch' && inputs.release_url || github.event.release.upload_url }}
          asset_path: linuxBinaries/Clave.zip
          asset_name: Clave-linux.zip
          asset_content_type: application/zip