name: CI/CD Workflow

permissions:
  contents: write
  pull-requests: read

on:
  push:
    branches: [pipeline]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for the release (e.g., 1.1.0)'
        required: true

jobs:
  build:
    name: Build and Test on Push
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Wails Dependencies
        run: |
          mkdir -p ../github
          cd ../github
          git clone https://github.com/wailsapp/wails.git
          cd wails
          git checkout v3-alpha
          cd v3/cmd/wails3
          go install
          cd ../../../..
          pwd
          ls -la

      - name: Update go.mod
        run: |
          sed -i '' 's|../../Project/github/wails/v3|../github/wails/v3|g' go.mod
          cat go.mod

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: wails3 build

  release:
    name: Create Release
    runs-on: macos-latest
    needs: [build]
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Get Merged PR Details
        id: changelog
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          echo "changes=$(gh pr list --repo ${{ github.repository }} --state merged --json title,author --jq '.[].title + \" by @\" + .author.login' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_ENV
          echo "contributors=$(gh pr list --repo ${{ github.repository }} --state merged --json author --jq '.[].author.login' | sort | uniq | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true
        
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Wails Dependencies
        run: |
          mkdir -p ../github
          cd ../github
          git clone https://github.com/wailsapp/wails.git
          cd wails
          git checkout v3-alpha
          cd v3/cmd/wails3
          go install
          cd ../../../..
          pwd
          ls -la

      - name: Update go.mod
        run: |
          sed -i '' 's|../../Project/github/wails/v3|../github/wails/v3|g' go.mod
          cat go.mod

      - name: Build Release Binaries
        run: |
          mkdir -p darwinBinaries
          wails3 package
          zip -r Clave.zip bin/Clave.app
          mv Clave.zip darwinBinaries/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ github.event.inputs.version }}"
          name: "Version v${{ github.event.inputs.version }}"
          body: |
            ## What's Changed
            ${{ env.changes }}
            ## New Contributors
            ${{ env.contributors }}
          draft: false
          files: darwinBinaries/Clave.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
